version: '3'

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"

  migrations:
    image: project
    build: .
    command: python migrations.py
    depends_on:
      - db

  web:
    image: project
    command: python web.py
    ports: 
      - "8888:8080"
    depends_on:
      - db
      - migrations

  fetch_worker:
    image: project
    command: python fetch_worker.py
    depends_on:
      - db
      - migrations
  